---
- name: "this is our first play"
  hosts: deploy
  tasks:
    - name: "login and pushing in docker"
      command: |
               echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: "pull"
      command: |
               docker pull reehanruhullah/dataphion_prac:tagname
    - name: "run"
      command: |
               docker run 