
---
- hosts: deploy
  become: no
  gather_facts: no
  vars:
    docker_registry_url: "https://hub.docker.com"
    docker_registry_username: "reehanruhullah"
    docker_registry_password: "{{ password }}"
  tasks:
    - name: Login to Docker registry
      command: docker login -u "{{ docker_registry_username }}" -p "{{ docker_registry_password }}" "{{ docker_registry_url }}"
