
---
- hosts: deploy
  become: no
  gather_facts: no
  vars:
    docker_registry_password: "{{ password }}"

  tasks:
    - name: Login to docker registry
      shell: docker login {{https://hub.docker.com}}  -u {{reehanruhullah}} -p "{{ docker_registry_password }}"

    - name: pull image from docker hub
      shell: "docker pull reehanruhullah/dataphion_prac:tagname"

    - name: docker run
      shell: docker run  -it reehanruhullah/dataphion_prac:tagname