---
- name: "this is our first play"
  hosts: deploy
  tasks:
    - name: "login and pushing in docker"
      command: |
               echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
               docker image build -t reehanruhullah/dataphion_prac:t .
               docker push reehanruhullah/dataphion_prac:tgit