
---
- hosts: deploy
  become: no
  gather_facts: no
  vars:
    docker_registry_password: "{{DOCKER_PASSWORD  }}"
  tasks:
    - name: Login to docker registry
      shell: docker login <docker hub url>  -u <reehanruhullah> -p "{{ docker_registry_password }}"

    - name: pull image from docker hub
      shell: "docker pull reehanruhullah/dataphion_prac:tagname"

    - name: docker run
      shell: docker run --init -d -ti reehanruhullah/dataphion_prac:tagname