on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: ubuntu
        
        steps:
            - run: node --version
            - run: npm --version
            - run: npm install
            - uses: actions/checkout@v4
            - run: node index.js
