name: Building yml 
on: push

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
        - run: node --version
        - run: npm --version
        - uses: actions/checkout@v4
        - run: node index.js
