on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - run: node --version
            - run: npm --version
            - uses: actions/checkout@v4
            
            - run: node index.js
            - name: build and push image
              run: 
                echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "reehanruhullah/dataphion_prac" --password-stdin
                docker image build -t reehanruhullah/dataphion_prac:tagname
                docker push reehanruhullah/dataphion_prac:tagname

