on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node Version
        run: node --version

      - name: NPM Version
        run: npm --version

      - name: Install Dependencies
        run: npm install

      - name: Run Node Application
        run: node index.js

