on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: 
          - self-hosted
          - ubutt
        steps:
          
            
            - uses: actions/checkout@v4
            
            - name: Log in to Docker Hub
              run: |
                ansible-playbook ansible.yml ansible/arpi.txt 

